### ISSUE TITLE
Docker for Mooshak 1.6.3 but with newer C++ and Python version

### ISSUE THREAD

**Issue by wahyudierwin** [mooshak-dcc/docker-mooshak#2]
Hi @josepaiva94 ,

I would like to know that if it is possible to create a docker image for Mooshak 1.6 version but with newer C++ and Python 3. Because Mooshak 1.6 is more than enough for me.

Thanks in advance!

**Comment by josepaiva94** [comment]
Hi @wahyudierwin ,

Just published https://hub.docker.com/layers/mooshak/mooshak/starter-1.6.6/

**Comment by wahyudierwin** [comment]
Perfect! Thanks a lot, @josepaiva94 .
